---
title: "Se aprende haciendo M1"
author: "Nayeli Peña Martínez"
date: "2024-09-14"
output: github_document
---

# Pon a prueba tu conocimiento y acepta el desafío. Calcula estos items, genera los resultados en MD y sube los resultados a tu github. 

```{r}
library(dplyr)

data <-  read.csv("C:\\Users\\nayel\\OneDrive\\Escritorio\\BETAMETRICA\\MÓDULO 1\\BASES DE DATOS\\BASES_DATOS_BASES_ZS2ZD2\\Iowa_Liquor_Sales.csv",
                  stringsAsFactors = F,
                  header=T)

datos <- data %>% 
  mutate(Sale..Dollars.=(as.numeric(substr(data$Sale..Dollars.,2,15))),
         City=toupper(City),
         Store.Name=toupper(Store.Name),
         Date=as.Date(Date,format="%m/%d/%Y"),
         anio=lubridate::year(Date)) %>% 
  rename(ventas=Sale..Dollars.,
         ciudad=City,
         categoria=Category.Name,
         nombre_tienda=Store.Name)

```

##  ¿Cuál el top 5 de tiendas (promedio de ventas), para el año 2016, para la ciudad CEDAR RAPIDS?

```{r}
datos %>% 
  filter(ciudad =="CEDAR RAPIDS" & anio==2016) %>% 
  group_by(nombre_tienda,ciudad,anio) %>%
  summarise(promedio_ventas=mean(ventas)) %>% 
  arrange(-promedio_ventas) %>% 
  head(5)
```

## ¿Cuáles fueron los 5 últimos vendedores (promedio de ventas, para el 2016, para DAVENPORT)? 

```{r}
datos %>% 
  filter(ciudad =="DAVENPORT" & anio==2016) %>% 
  group_by(nombre_tienda,ciudad,anio) %>%
  summarise(promedio_ventas=mean(ventas)) %>% 
  arrange(promedio_ventas) %>% 
  head(5)
```

## ¿Cuál es el top 5 de productos más vendidos, para el 2016 y 2017, por ciudad? 

```{r}
datos %>% 
  filter(anio == 2017 | anio == 2016) %>%
    group_by(ciudad, anio, Item.Description) %>%
    summarise(ventas_totales = sum(ventas, na.rm = TRUE)) %>%
    slice_max(order_by = ventas_totales, n = 5)
```

